package entity;
// Generated 2016-11-11 9:13:29 by Hibernate Tools 5.1.0.Beta1

/**
 * Assistance generated by hbm2java
 */
public class Assistance implements java.io.Serializable {

	private String workId;
	private String sourceSet;
	private String name;
	private String phone;
	private String email;
	private String password;
	private String usertype;
	private String username;
	private String agentid;
	private Integer flag;

	public Assistance() {
	}

	public Assistance(String workId, String name, String phone, String email, String password, String usertype) {
		this.workId = workId;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.usertype = usertype;
	}

	public Assistance(String workId, String sourceSet, String name, String phone, String email, String password,
			String usertype, String username, String agentid, Integer flag) {
		this.workId = workId;
		this.sourceSet = sourceSet;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.usertype = usertype;
		this.username = username;
		this.agentid = agentid;
		this.flag = flag;
	}

	public String getWorkId() {
		return this.workId;
	}

	public void setWorkId(String workId) {
		this.workId = workId;
	}

	public String getSourceSet() {
		return this.sourceSet;
	}

	public void setSourceSet(String sourceSet) {
		this.sourceSet = sourceSet;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAgentid() {
		return this.agentid;
	}

	public void setAgentid(String agentid) {
		this.agentid = agentid;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
